### ISSUE TITLE
Try `brew bundle`

### ISSUE THREAD

**Issue by metruzanca** [sammi-turner/MacOS-Dotfiles#1]
Hello fellow Degen,

Was lurking thru your repos and found this one. I noticed you did what I used to do with brew apps, so I thought I'd let you know that theres this handy feature of brew called bundle, that lets you install your system packages from a `Brewfile` e.g.

```brew
brew git
brew ffmpeg
brew yt-dlp
brew node
brew pnpm
```

I found out about it at my last position and used it to [setup my current macbook](https://github.com/metruzanca/dotfiles/blob/master/os/macos/Brewfile). Works like a charm.

You can generate a Brewfile with `brew bundle dump`. (I then went in and organized it a bit)

[Heres a good tl;dr; + best practices](https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f)

**Comment by sammi-turner** [comment]
Thank you for the tip!
